spring:
  application:
    name: Shoe_Mart_Product
  datasource:
    url: jdbc:mysql://localhost:3306/shoe_mart
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Rgukt@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    
server:
  port: 8085
eureka:
  client: 
    service-url:
      defaultZone: http://localhost:8000/eureka/